### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by EikeDehling**
Hi Ilya Markov,

thanks for creating the PyClick package - i'm using it at work and it has been a great help to have these pre-implemented models!

I'm hereby submitting a pull request that makes the code python3 compatible and i'm dropping some  nonexistant imports from the example script.

Please let me know if you're open to accept pull request and/or any feedback or comments you have on my changes.

Thanks & have a good weekend!

Eike Dehling

### CODE REVIEW

**Comment by markovi** [comment]
Hi Eike,

Thank you, this is very nice of you. I will review and merge your changes sometime early January (for now there is lots of work to finish before the Xmas break).

Thanks again,
Ilya.

**Comment by EikeDehling** [comment]
Great, thanks, let me know. Changes are pretty small luckily. Happy holidays!

**Review by varepsilon — APPROVED** [review]
Thanks!

**Comment by Rowing0914** [comment]
Hiya!
I love this repo but I'd like to just confirm like,
This isn't actually merged yet, is this?

**Comment by SuzanaK** [comment]
Any news on merging this PR?

**Comment by markovi** [comment]
I have just merged the changes.

**Review by markovi — COMMENTED** [review]
All changes look good.

**Pull request merged**
